apiVersion: v1
kind: Service
metadata:
  name: kube-etcd
  namespace: kube-system
  labels:
    app: kubernetes
spec:
  selector:
    app: kubernetes
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-etcd
  namespace: kube-system
  labels:
    app: kubernetes
subsets:
- addresses:
  - ip: xxxx
    nodeName: control
  ports:
  - name: kube-etcd
    port: 2381
